kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-web4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-web4
    spec:
      containers:
      - name: nginx-web4
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: configmap-volume
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: configmap-volume
        configMap:
          name: nginx-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }
