kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-web4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-web4
  template:
    metadata:
      labels:
        app: nginx-web4
    spec:
      containers:
      - name: nginx-web4
        image: nginx
        ports:
          - containerPort: 80
        volumeMounts:
          - name: html-ngix-volume
            mountPath: /usr/share/nginx/html
      volumes:
        - name: html-ngix-volume
          hostPath:
            path: /home/ccaciquey/html-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cm
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }
